### ISSUE TITLE
User Story 16: Final Documentation (8 points)

### ISSUE THREAD

**Issue by SimonMoynihan33** [SimonMoynihan33/GameGrade#22]
As a developer, I wish to complete and finalize documentation for the site so that it’s easy to understand how the site works and how to maintain it.

## Acceptance Criteria
- Documentation should include setup instructions, API integrations, and descriptions of key features.
- The README file should be clear, well-organized, and easy to follow.
- Documentation should cover both developer setup and user instructions.
- Separate file for testing with extensive testing using tables, validators, manual testing and (optional) automated testing.

## Tasks
- [ ] Write comprehensive documentation for the project, including setup instructions and feature descriptions.
- [ ] Ensure the README file is well-structured and includes all necessary information.
- [ ] Test every functionality and document, run all code through validators.
- [ ] Review and finalize documentation to ensure accuracy and clarity.
